server:
  port: 8082

spring:
  application:
    name: transaction-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/magasin_transactions
    username: postgres
    password: cytech
  
  jpa:
    hibernate:
      ddl-auto: update  # Mode normal : conserve les donn√©es
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: magasindisque@gmail.com
    password: pwfp ihji yiel woso
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Configuration Actor System
actor:
  system:
    name: transaction-service-actors
    dispatcher:
      core-pool-size: 10
      max-pool-size: 50
    supervision:
      strategy: restart
      max-retries: 3

# Configuration Feign clients
feign:
  client:
    config:
      user-service:
        connectTimeout: 5000
        readTimeout: 5000
